name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:

  electron:

    name: Build Electron For ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Windows Garbage
        if: runner.os == 'Windows'
        run: npm install -g node-gyp

      - name: Install Node Modules
        run: npm install --prefix client --cwd client

      - name: Package App
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: npm run buildElectron --prefix client --cwd client

  website:

    name: Deploy To Production Instance
    runs-on: ubuntu-latest

    steps:

      - name: Execute AWS SSH Commands (Update Repo and Redeploy)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ~/cs414-f20-The-B-Team/scripts/deploy.sh
